example.property: "h2 property"
spring:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    database: "H2"
    openInView: "false"
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
  datasource:
    url: "jdbc:h2:tcp://localhost/~/test"
    username: "sa"
    password:
    driverclassname: "org.h2.Driver"
    schema: "classpath:sql/schema.sql"
    data: "classpath:sql/data.sql"

