example.property: "default property"
spring:
  jpa:
    datasource: "mysql"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
  datasource:
    url: "jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false"
    username: "devdb"
    password: "Saasvideo"
    driverClassName: "com.mysql.cj.jdbc.Driver"

